export const userStories = [
  {
    firstName: 'Gabriel',
    id: 1,
    profileImage: require('./assets/images/default_profile.png'),
  },
  {
    firstName: 'Licha',
    id: 2,
    profileImage: require('./assets/images/default_profile.png'),
  },
  {
    firstName: 'Angela',
    id: 3,
    profileImage: require('./assets/images/default_profile.png'),
  },
  {
    firstName: 'Reco',
    id: 4,
    profileImage: require('./assets/images/default_profile.png'),
  },
  {
    firstName: 'Chris',
    id: 5,
    profileImage: require('./assets/images/default_profile.png'),
  },
  {
    firstName: 'Reene',
    id: 6,
    profileImage: require('./assets/images/default_profile.png'),
  },
  {
    firstName: 'Anne',
    id: 7,
    profileImage: require('./assets/images/default_profile.png'),
  },
  {
    firstName: 'Rose',
    id: 8,
    profileImage: require('./assets/images/default_profile.png'),
  },
  {
    firstName: 'Tony',
    id: 9,
    profileImage: require('./assets/images/default_profile.png'),
  },
];

export const userPosts = [
  {
    firstName: 'Allison',
    lastName: 'Becker',
    location: 'Boston, MA',
    image: require('./assets/images/firstimage.jpeg'),
    profileImage: require('./assets/images/default_profile.png'),
    likes: 1232,
    comments: 24,
    bookmarks: 55,
    id: 1,
  },
  {
    firstName: 'Mike',
    lastName: 'Reene',
    location: 'Allianz, MA',
    image: require('./assets/images/secondimages.jpeg'),
    profileImage: require('./assets/images/default_profile.png'),
    likes: 132,
    comments: 24,
    bookmarks: 556,
    id: 2,
  },
  {
    firstName: 'Doris',
    lastName: 'Owo',
    location: 'Canada',
    image: require('./assets/images/thirdimages.jpeg'),
    profileImage: require('./assets/images/default_profile.png'),
    likes: 32,
    comments: 44,
    bookmarks: 5,
    id: 3,
  },
  {
    firstName: 'Roy',
    lastName: 'Keex',
    location: 'Laine, MA',
    image: require('./assets/images/fourthimages.jpeg'),
    profileImage: require('./assets/images/default_profile.png'),
    likes: 432,
    comments: 324,
    bookmarks: 535,
    id: 4,
  },
  {
    firstName: 'Gabriel',
    lastName: 'Becker',
    location: 'United Kingdom',
    image: require('./assets/images/fifthimages.jpeg'),
    profileImage: require('./assets/images/default_profile.png'),
    likes: 232,
    comments: 454,
    bookmarks: 55,
    id: 5,
  },
];
